### ISSUE TITLE
how can my deployment reference the service account in a different namespace?

### ISSUE THREAD

**Issue by xhzuo** [Azure/azure-workload-identity#449] opened 2022-05-15 09:02 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
This is not an issue, but a how to question. 
How can my deployment reference the service account in a different namespace?

**Comment by aramase** [comment] 2022-05-16 15:50
> How can my deployment reference the service account in a different namespace?

Pods can only reference service account that exists in the same namespace. Referencing service accounts from different namespace is not possible. This is imposed at the API layer.

If you need to use workload identity with your deployment in namespace, then you would need to annotate the service account (`sa`) in namespace and use that service account in your deployment in same namespace. The federated identity credential will then need to be configured for this service account which is in your namespace.

**Comment by aramase** [comment] 2022-06-03 17:28
Closing this issue as by design service account needs to be in the same namespace as the resource referencing it. Please feel free to reopen if you have any other questions.

**Closed by aramase** 2022-06-03 17:28 UTC
Labels: enhancement
