### ISSUE TITLE
azure-wi-webhook-controller-manager pods are stuck in CrashLoopBackOff after cert-manager is installed

### ISSUE THREAD

**Issue by oleksandrkudin** [Azure/azure-workload-identity#599] opened 2022-10-18 16:18 UTC
**azure-wi-webhook-controller-manager pods are stuck in CrashLoopBackOff after cert-manager is installed**

After cert-manager is deleted, azure-wi-webhook-controller-manager pods work fine. 

**Steps To Reproduce**
1. Install workload-identity-webhook

```
export AZURE_TENANT_ID="$(az account show -s <AzureSubscriptionID> --query tenantId -otsv)"

helm repo add azure-workload-identity https://azure.github.io/azure-workload-identity/charts
helm repo update
helm install workload-identity-webhook azure-workload-identity/workload-identity-webhook \
   --namespace cluster-config \
   --create-namespace \
   --set azureTenantID="${AZURE_TENANT_ID}"
```

2. Install cert-manager

```
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.10.0 \
  --set installCRDs=true \
  --set default-issuer-name=letsencrypt-public-nginx \
  --set default-issuer-kind=ClusterIssuer
```

4. Recreate pod - `kubectl rollout restart deployment/azure-wi-webhook-controller-manager -n cluster-config`

5. Check pods status - `kubectl get pods -n cluster-config`

**Expected behavior**

azure-wi-webhook-controller-manager pods are up and running. 

**Logs**

Only one azure-wi-webhook-controller-manager pod was restarted to not affect applications.

```
~ kubectl get pods -n cluster-config
NAME                                                              READY   STATUS             RESTARTS       AGE
azure-wi-webhook-controller-manager-566c7df7c4-2t7bt              1/1     Running            7 (90m ago)    97m
azure-wi-webhook-controller-manager-566c7df7c4-ggqd4              0/1     CrashLoopBackOff   14 (56s ago)   50m
```

```
~ kubectl logs azure-wi-webhook-controller-manager-566c7df7c4-ggqd4 -n cluster-config
I1018 15:53:13.054235       1 logr.go:261] entrypoint "msg"="initializing metrics backend"  "backend"="prometheus"
I1018 15:53:13.054337       1 logr.go:261] entrypoint "msg"="setting up manager"  "userAgent"="azure-workload-identity/webhook/v0.13.0 (linux/amd64) 46c5137/2022-08-31-23:36"
I1018 15:53:14.260050       1 request.go:601] Waited for 1.012664307s due to client-side throttling, not priority and fairness, request: GET:https://10.2.0.1:443/apis/storage.k8s.io/v1?timeout=32s
I1018 15:53:14.363479       1 logr.go:261] controller-runtime/metrics "msg"="Metrics server is starting to listen"  "addr"=":8095"
I1018 15:53:14.363806       1 logr.go:261] entrypoint "msg"="setting up cert rotation"
I1018 15:53:14.363976       1 logr.go:261] entrypoint "msg"="starting manager"
I1018 15:53:14.364415       1 internal.go:362]  "msg"="Starting server" "addr"={"IP":"::","Port":8095,"Zone":""} "kind"="metrics" "path"="/metrics"
I1018 15:53:14.364463       1 logr.go:261] cert-rotation "msg"="starting cert rotator controller"
I1018 15:53:14.365268       1 internal.go:362]  "msg"="Starting server" "addr"={"IP":"::","Port":9440,"Zone":""} "kind"="health probe"
I1018 15:53:14.365476       1 controller.go:185]  "msg"="Starting EventSource" "controller"="cert-rotator" "source"="&{{%!s(*v1.Secret=&{{ } {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} <nil> map[] map[] }) %!s(*cache.informerCache=&{0xc00061b540}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"
I1018 15:53:14.365521       1 controller.go:185]  "msg"="Starting EventSource" "controller"="cert-rotator" "source"="&{{%!s(*unstructured.Unstructured=&{map[apiVersion:admissionregistration.k8s.io/v1 kind:MutatingWebhookConfiguration]}) %!s(*cache.informerCache=&{0xc00061b540}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"
I1018 15:53:14.365541       1 controller.go:193]  "msg"="Starting Controller" "controller"="cert-rotator"
```

**Environment**

- Kubernetes version (use `kubectl version`):

```
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.6
```

- Cloud provider or hardware configuration: Azure AKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by aramase** [comment] 2022-10-18 17:24
@oleksandrkudin I just tried this in `v1.25.0` kind cluster, `v1.23.8` and `v1.24.6` AKS clusters and don't see any issue. The webhook pods restart fine on `kubectl rollout restart deployment/azure-wi-webhook-controller-manager -n <namespace>`. Are you able to reproduce this consistently? 

The azwi webhook uses [open-policy-agent/cert-controller](https://github.com/open-policy-agent/cert-controller) for certificates and doesn't rely on cert-manager, so installing/uninstalling cert-manager _shouldn't_ impact the wi pods.

**Comment by oleksandrkudin** [comment] 2022-10-18 19:08
@aramase Before i created issue i was able to reproduce error for two weeks many times. I even had to disable cert-manager. So issue was consistent. Now i cannot reproduce it. I did many changes today during troubleshooting. Hopefully some change fixed issue and it will not come up again.

**Comment by aramase** [comment] 2022-10-18 19:46
> @aramase Before i created issue i was able to reproduce error for two weeks many times. I even had to disable cert-manager. So issue was consistent. Now i cannot reproduce it. I did many changes today during troubleshooting. Hopefully some change fixed issue and it will not come up again.

Thanks for the update! I'm going to close this issue now because there is no repro and it's not consistent. Feel free to update or reopen if you run into similar issue.

**Comment by oleksandrkudin** [comment] 2022-10-19 12:17
@aramase Could you please reopen this issue. Today issue comes up again.

It was 39 unsuccessful restart.
It stuck on `controller.go:193]  "msg"="Starting Controller" "controller"="cert-rotator"`. See two logs snippets - during issue and normal start.

```
kubectl get pods -n cluster-config
NAME                                                              READY   STATUS             RESTARTS         AGE
azure-wi-webhook-controller-manager-6d848bc7c8-6gvft              1/1     Running            0                17h
azure-wi-webhook-controller-manager-6d848bc7c8-nh7xw              0/1     CrashLoopBackOff   39 (3m24s ago)   17h

kubectl logs azure-wi-webhook-controller-manager-6d848bc7c8-nh7xw -n cluster-config
I1019 11:53:43.240124       1 logr.go:261] entrypoint "msg"="initializing metrics backend"  "backend"="prometheus"
I1019 11:53:43.240302       1 logr.go:261] entrypoint "msg"="setting up manager"  "userAgent"="azure-workload-identity/webhook/v0.13.0 (linux/amd64) 46c5137/2022-08-31-23:36"
I1019 11:53:44.340826       1 request.go:601] Waited for 1.046738614s due to client-side throttling, not priority and fairness, request: GET:https://10.2.0.1:443/apis/source.toolkit.fluxcd.io/v1beta1?timeout=32s
I1019 11:53:44.495824       1 logr.go:261] controller-runtime/metrics "msg"="Metrics server is starting to listen"  "addr"=":8095"
I1019 11:53:44.496141       1 logr.go:261] entrypoint "msg"="setting up cert rotation"
I1019 11:53:44.496314       1 logr.go:261] entrypoint "msg"="starting manager"
I1019 11:53:44.496635       1 internal.go:362]  "msg"="Starting server" "addr"={"IP":"::","Port":8095,"Zone":""} "kind"="metrics" "path"="/metrics"
I1019 11:53:44.496664       1 logr.go:261] cert-rotation "msg"="starting cert rotator controller"
I1019 11:53:44.496668       1 internal.go:362]  "msg"="Starting server" "addr"={"IP":"::","Port":9440,"Zone":""} "kind"="health probe"
I1019 11:53:44.496842       1 controller.go:185]  "msg"="Starting EventSource" "controller"="cert-rotator" "source"="&{{%!s(*v1.Secret=&{{ } {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} <nil> map[] map[] }) %!s(*cache.informerCache=&{0xc00038f5a0}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"
I1019 11:53:44.496876       1 controller.go:185]  "msg"="Starting EventSource" "controller"="cert-rotator" "source"="&{{%!s(*unstructured.Unstructured=&{map[apiVersion:admissionregistration.k8s.io/v1 kind:MutatingWebhookConfiguration]}) %!s(*cache.informerCache=&{0xc00038f5a0}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"
I1019 11:53:44.496888       1 controller.go:193]  "msg"="Starting Controller" "controller"="cert-rotator"
```

After i deleted cert-manager and ClusterIssuer (resource of cert-manager)  - everything is OK

```
~ kubectl get pods -n cluster-config
NAME                                                              READY   STATUS    RESTARTS        AGE
azure-wi-webhook-controller-manager-6d848bc7c8-6gvft              1/1     Running   0               17h
azure-wi-webhook-controller-manager-6d848bc7c8-nh7xw              1/1     Running   41 (6m8s ago)   17h

~ kubectl logs azure-wi-webhook-controller-manager-6d848bc7c8-nh7xw -n cluster-config
I1019 12:04:08.249281       1 logr.go:261] entrypoint "msg"="initializing metrics backend"  "backend"="prometheus"
I1019 12:04:08.249412       1 logr.go:261] entrypoint "msg"="setting up manager"  "userAgent"="azure-workload-identity/webhook/v0.13.0 (linux/amd64) 46c5137/2022-08-31-23:36"
I1019 12:04:09.399314       1 request.go:601] Waited for 1.045839755s due to client-side throttling, not priority and fairness, request: GET:https://10.2.0.1:443/apis/flowcontrol.apiserver.k8s.io/v1beta2?timeout=32s
I1019 12:04:09.454205       1 logr.go:261] controller-runtime/metrics "msg"="Metrics server is starting to listen"  "addr"=":8095"
I1019 12:04:09.454547       1 logr.go:261] entrypoint "msg"="setting up cert rotation"
I1019 12:04:09.454833       1 logr.go:261] entrypoint "msg"="starting manager"
I1019 12:04:09.455282       1 logr.go:261] cert-rotation "msg"="starting cert rotator controller"
I1019 12:04:09.455358       1 internal.go:362]  "msg"="Starting server" "addr"={"IP":"::","Port":8095,"Zone":""} "kind"="metrics" "path"="/metrics"
I1019 12:04:09.455423       1 controller.go:185]  "msg"="Starting EventSource" "controller"="cert-rotator" "source"="&{{%!s(*v1.Secret=&{{ } {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} <nil> map[] map[] }) %!s(*cache.informerCache=&{0xc000325620}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"
I1019 12:04:09.455450       1 controller.go:185]  "msg"="Starting EventSource" "controller"="cert-rotator" "source"="&{{%!s(*unstructured.Unstructured=&{map[apiVersion:admissionregistration.k8s.io/v1 kind:MutatingWebhookConfiguration]}) %!s(*cache.informerCache=&{0xc000325620}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"
I1019 12:04:09.455456       1 internal.go:362]  "msg"="Starting server" "addr"={"IP":"::","Port":9440,"Zone":""} "kind"="health probe"
I1019 12:04:09.455469       1 controller.go:193]  "msg"="Starting Controller" "controller"="cert-rotator"
I1019 12:04:10.540997       1 logr.go:261] cert-rotation "msg"="no cert refresh needed"
I1019 12:04:10.541074       1 logr.go:261] cert-rotation "msg"="certs are ready in /certs"
I1019 12:04:10.541708       1 controller.go:227]  "msg"="Starting workers" "controller"="cert-rotator" "worker count"=1
I1019 12:04:10.542260       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I1019 12:04:12.479970       1 logr.go:261] cert-rotation "msg"="CA certs are injected to webhooks"
I1019 12:04:12.480038       1 logr.go:261] entrypoint "msg"="setting up webhook server"
I1019 12:04:12.480134       1 logr.go:261] entrypoint "msg"="registering webhook to the webhook server"
I1019 12:04:12.480235       1 server.go:216] controller-runtime/webhook/webhooks "msg"="Starting webhook server"
I1019 12:04:12.480306       1 server.go:148] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-v1-pod"
I1019 12:04:12.480497       1 logr.go:261] controller-runtime/certwatcher "msg"="Updated current TLS certificate"
I1019 12:04:12.480670       1 logr.go:261] controller-runtime/webhook "msg"="Serving webhook server"  "host"="" "port"=9443
I1019 12:04:12.480736       1 logr.go:261] controller-runtime/certwatcher "msg"="Starting certificate watcher"
```

**Comment by oleksandrkudin** [comment] 2022-10-20 04:33
Issue happens not immetiately after cert-manager and ClusterIssue install but some hours after. Today it happened again and only one pod of azure-wi-webhook-controller-manage, second pod is working . But starting to run immetiately after i delete cert-manager and ClusterIssue.

**Comment by oleksandrkudin** [comment] 2022-10-20 09:52
@aramase I increased limits cpu=200m, memory=60Mi and pods automatically went to up and running state. So i am experimenting with resource limits.

**Comment by aramase** [comment] 2022-10-20 16:35
> Issue happens not immetiately after cert-manager and ClusterIssue install but some hours after. Today it happened again and only one pod of azure-wi-webhook-controller-manage, second pod is working . But starting to run immetiately after i delete cert-manager and ClusterIssue.

Are you restarting the webhook pod after some time and is that's what causing it to crash? Trying to understand what's causing the restart of webhook pod after few hours. 

>  I increased limits cpu=200m, memory=60Mi and pods automatically went to up and running state. So i am experimenting with resource limits.

Do you have enough resources on the node where webhook pods are deployed? I've let cert-manager running on my cluster on a while and I don't see any issue so far.

If you're using AKS, I would recommend using the managed add-on for workload identity: https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview. FYI, The managed add-on is officially supported by AKS, while the OSS solution (installing from this repo) is only supported via GitHub (ref: https://github.com/Azure/azure-workload-identity#support)

**Comment by aramase** [comment] 2022-10-20 16:42
```bash
cert-manager         cert-manager-69b456d85c-z5k5f                         1/1     Running   0             47h
cert-manager         cert-manager-cainjector-5f44d58c4b-j7xg6              1/1     Running   0             47h
cert-manager         cert-manager-webhook-566bd88f7b-qdnqq                 1/1     Running   0             47h
cluster-config       azure-wi-webhook-controller-manager-9fb4dd748-t245j   1/1     Running   0             6s
cluster-config       azure-wi-webhook-controller-manager-9fb4dd748-wgfbp   1/1     Running   0             4s
```

Restarted the webhook pods and they're running fine. Are you able to reproduce this on any other cluster or just one?

**Comment by oleksandrkudin** [comment] 2022-10-20 17:02
@aramase - After i increased default limits for cpu and memory everything work fine.

**Comment by aramase** [comment] 2022-11-01 00:10
This might be isolated to a single cluster and resource constraints, so I'll close this issue now as we have no repro in CI. Please feel free to open a new issue if you have any questions.

**Closed by aramase** 2022-11-01 00:10 UTC
Labels: bug
