### ISSUE TITLE
[AKS] "system:serviceaccount:workload-identity:azure-wi-webhook-admin" cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope

### ISSUE THREAD

**Issue by pockyhe** [Azure/azure-workload-identity#777] opened 2023-03-06 08:15 UTC
**Describe the bug**
We enable workload identity in our aks to access Azure Resources. It works well. suddenly we found our service cannot access azure resources today.
The only changes in this AKS is that we reinstall cert-manager 6 days argo. We don't know what caused this problem.

For fixing it, we helm reinstall it, it works well.

**Logs**
E0306 07:49:05.332724       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration: failed to list admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration: mutatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:workload-identity:azure-wi-webhook-admin" cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
W0306 07:49:42.898523       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: failed to list admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration: mutatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:workload-identity:azure-wi-webhook-admin" cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
E0306 07:49:42.898557       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration: failed to list admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration: mutatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:workload-identity:azure-wi-webhook-admin" cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
W0306 07:49:49.023471       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:workload-identity:azure-wi-webhook-admin" cannot list resource "serviceaccounts" in API group "" at the cluster scope
E0306 07:49:49.023505       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch *v1.ServiceAccount: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:workload-identity:azure-wi-webhook-admin" cannot list resource "serviceaccounts" in API group "" at the cluster scope
W0306 07:50:29.890010       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:workload-identity:azure-wi-webhook-admin" cannot list resource "serviceaccounts" in API group "" at the cluster scope
E0306 07:50:29.890049       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch *v1.ServiceAccount: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:workload-identity:azure-wi-webhook-admin" cannot list resource "serviceaccounts" in API group "" at the cluster scope
W0306 07:50:33.080530       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: failed to list admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration: mutatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:workload-identity:azure-wi-webhook-admin" cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
E0306 07:50:33.080567       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration: failed to list admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration: mutatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:workload-identity:azure-wi-webhook-admin" cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope

**Environment**

**Comment by aramase** [comment] 2023-03-06 18:18
@fewkso @pockyhe How are you installing workload identity on AKS? Are you installing it using the helm charts from this repo or enabling the AKS add-on for workload identity? The error message seems to indicate the `ClusterRole` might have been deleted which caused the issue.

@karataliu Any rollout in AKS that could cause this issue?

**Comment by fewkso** [comment] 2023-03-06 18:56
@aramase It was installed 16 days ago, right after the cluster install, with helm with only the azureTenantID as value. It worked for a while then this morning a deployment was failing, workload identity env vars weren't injected anymore. I ended up looking in wi webhook pods logs and there was these errors.

**Comment by adminnz** [comment] 2023-03-06 22:26
I have the same issue, the ClusterRole and ClusterRoleBinding were somehow deleted, but I don't know how they were deleted.

I had to uninstall & reinstall the helm chart again.

This is rather worrying if the ClusterRole & ClusterRoleBindings are somehow getting deleted without user interaction.

**Comment by aramase** [comment] 2023-03-06 23:02
The only possible entity that deleted the `ClusterRole` and `ClusterRoleBinding` is AKS here. I've tagged @karataliu to look into this from the AKS side.

**Comment by boney9** [comment] 2023-03-06 23:56
We had a similar issue, and the way it was resolved was to re-install the helm chart.

**Comment by aramase** [comment] 2023-03-07 00:20
This is a bug with the AKS add-on code that's causing deletion of `ClusterRole` and `ClusterRoleBinding` even when WI is installed using helm charts. They are working on the fix and this is the bug tracking it: https://github.com/Azure/AKS/issues/3510. Please follow the issue for more details. @karataliu will update that issue with the ETA for the fix.

For anyone who comes across this issue, if your `ClusterRole` or `ClusterRoleBinding` is missing, the recommendation is to reinstall workload identity using the helm charts.

**Comment by karataliu** [comment] 2023-03-07 10:09
Thanks very much for reporting the issue.

AKS side is deploying the fix, ETA is ~1 day.

This issue will impact open source version of workload-identity.

Please reinstall workload-identity helm release or use [AKS integrated workload identity](https://aka.ms/aks/wi) as a fix.

**Comment by fewkso** [comment] 2023-03-07 12:25
@aramase @karataliu Thanks to you guys for the quick investigation 😄 

Also, I don't know how many AKS clusters use workload identity out there, but a lot of them will only exhibit the problem once pods are restarted and that could be in days or weeks. Would there be any way to email clients with clusters using workload identity about this issue? I know it's still in preview but it's already used in production in some cases.

**Comment by liamgib** [comment] 2023-03-07 12:32
Thanks @karataliu / @aramase 

+1 to @fewkso comment, we just spent hours debugging this and going back to forward w/ AKS Support until the issue was discovered. It's in preview, so happy to accept outages here and there but the deletion of critical resources without any notice is hard to accept.

**Comment by pockyhe** [comment] 2023-03-07 13:51
@aramase @karataliu Thank all of you for investigation

**Comment by karataliu** [comment] 2023-03-08 05:41
@fewkso @liamgib Sorry about the inconvenience and much thanks for the kind reminder.
We have been actively working the notification, it is on the way. We'll keep improving on delivering the information in time.

**Comment by liamgib** [comment] 2023-03-08 06:50
Thank you @karataliu, I appreciate the effort and transparency on rectify the issue.

**Comment by SOFSPEEL** [comment] 2023-03-08 15:38
Having same problem, one thing I noticed about "workaround" is that killing the pods shown below is not enough, need to do helm uninstall and reinstall.

 helm uninstall workload-identity-webhook -n blah

Wondering if going to an older version of the helm install will be a better workaround?

![image](https://user-images.githubusercontent.com/1612646/223757632-c61fda6e-9452-4ea5-8cf1-566384eb66ca.png)

**Comment by davejhahn** [comment] 2023-03-08 19:30
Looking for some clarification here.... started running into this issue also and also came to the conclusion that re-installing workload-identity resolves the issue.

Clarification is on what the "fix" is.   Is this something that is being fixed on the Azure side or a fix to workload identity to handle ?

Just trying to understand if anywhere we have no encountered this if we will need to re-install an updated version of workload identity or if it will resolve itself.

**Comment by fewkso** [comment] 2023-03-08 19:45
@davejhahn @SOFSPEEL Workload identity webhook can be installed with the az command line without installing the helm chart. 

From what I understand, a bug introduced in an AKS cleanup job was deleting the workload identity `ClusterRole` and `ClusterRoleBinding` if the "managed" Workload Identity webhook wasn't used. 

Microsoft already fixed it on their side, but they won't undelete what they deleted. 

Reinstalling the chart fixes the problem, but just recreating the `ClusterRole` and `ClusterRoleBinding` fixes the problem.

**Comment by davejhahn** [comment] 2023-03-08 20:43
@fewkso ok thanks for the clarification.  And yep, aware that it can be installed with azure cli.   We have this all integrated into a terraform sub-module to create everything needed (and one part of that is deploying the helm chart).    Sounds like at this point, it's fixed, but we should re-install workload identity in all our clusters (and restarting any deployments).

**Comment by liamgib** [comment] 2023-03-08 23:35
I don't know if the fix has been applied to all regions yet, but just as an FYI the ClusterRole & ClusterRoleBinding's just got deleted from our AKS clusters again.

**Comment by pockyhe** [comment] 2023-03-09 02:04
@liamgib @aramase I faced same situation. After having reinstalled it, this bug happened again today

**Comment by mlabrum** [comment] 2023-03-09 07:45
We've hit this issue twice today, with about 5 hours in-between on two clusters.

Why isn't Microsoft notifying customers? This is a huge issue.

**Comment by Houley01** [comment] 2023-03-09 07:57
We've hit this issue three times today, with about 5 hours in-between on one cluster.

And we are getting the error in another cluster using Azure workload identity, we are just luck we have yet to have any pods reboot I am guessing.

Why isn't Microsoft notifying us? This is a MAJOR  issue.

**Comment by davejhahn** [comment] 2023-03-09 15:02
@Houley01 I agree this is a critical issue.  

If you think about it, every customer that uses workload identity outside of the managed version will run into this.  It more or less breaks any application reliant on it (eventually).   

Every customer that is in this scenario may or may not even be aware of the issue, and once they identify something is wrong, they have no idea what it is, and has to spend time researching it, and (hopefully) ending up here to read this thread.

But maybe they aren't finding this thread and pulling their hair out, and in the mean time, causing production outages, when a simple notification of a potential problem (and resolution) could be sent out.

I'd like to know why they are _inside_ our clusters deleting things in the first place.

**Comment by fewkso** [comment] 2023-03-09 15:13
Even though this feature is really nice and useful and people are eager to put in in place everywhere, it's still in _preview_, don't forget that.

The problem happened again on my clusters, so I just decided to switch to the [managed version](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster#install-the-aks-preview-azure-cli-extension). Problem fixed 😄

**Comment by miwithro** [comment] 2023-03-09 17:34
Hello,
  We have rolled out for this issue which is included in the "v20230226" release.  You can track the release for the particular region your cluster is in here: https://releases.aks.azure.com/#tabversion

**Comment by davejhahn** [comment] 2023-03-09 20:00
@miwithro I'm assuming this means that the issue is still going to be occurring until the status indicates it is complete for the region applicable to us?

Once it indicates it is complete, is there anything (aside from addressing the workaround described above) that needs to be done on the AKS side on our end?

**Comment by mlabrum** [comment] 2023-03-09 22:35
For anyone saying this is a preview Microsoft have depreciated the currently supported version (aad-pod-identity) and the directed link to https://azure.github.io/azure-workload-identity/docs/ does not mention anything about this being in preview
The only message being when you check the git repository under support https://github.com/Azure/azure-workload-identity 

```
IMPORTANT: As of Monday 10/24/2022, AAD Pod Identity is deprecated. As mentioned in the [announcement](https://cloudblogs.microsoft.com/opensource/2022/01/18/announcing-azure-active-directory-azure-ad-workload-identity-for-kubernetes/), AAD Pod Identity has been replaced with [Azure Workload Identity](https://azure.github.io/azure-workload-identity). Going forward, we will no longer add new features to this project in favor of Azure Workload Identity. We will continue to provide critical bug fixes until Azure Workload Identity reaches general availability. Following that, we will provide CVE patches until September 2023, at which time the project will be archived.
```

So anyone building new systems would choose to implement Azure Workload identity based on that information, this notice should mention that workload identity is not supported by Azure support and not to use it as its currently in preview.

That issue aside, Microsoft's AKS team _deleted_ resources in clusters, it doesn't matter if its from a supported product or not, they actively deleted resources and should have communicated to AKS users saying that they may have deleted resources from their AKS environments, not just ignore the problem, it doesn't matter _what_ was deleted, it matters that _something_ was deleted without communication.

This does not give me confidence in the AKS environment if Microsoft may delete resources from our clusters without any sort of communication, this issue alone had us burning through a day of clients time.

**Comment by karataliu** [comment] 2023-03-10 03:58
Thanks everyone for the kind comments. Here are some updates.

- Impact
In a recent release, AKS service  will trigger unexpectedly deletion of specific resource of workload identity open source project, including clusterrole and clusterrolebinding.
Besides the release rollout, any update operation to the AKS cluster will also trigger the deletion. This should explain why the resource got deleted more than 1 time.

- Brief RCA:
AKS side is working on cleaning up 'workload identity cluster role' when the AKS integrated workload identity is disabled state, the original intention was to clean up AKS integrated workload identity managed cluster role resource, but it missed the proper selector label. The result is the open source project cluster role resource also got deleted.
The fix adds proper label for the deletion operation, so that it will only affect AKS integrated workload identity managed resources.

- Fix timeline:
  - The fix completed in all regions on `UTC 2023-03-09 07:35:00`, it takes up to 24h to apply to existing clusters.
  - All new clusters would be not affected by the issue after above timestamp
  - All existing clusters would be not affected by the issue after up to 24h, i.e. `UTC 2023-03-10 07:35:00`

- Action needed:
  Please reinstall the open source helm chart or use AKS integrated feature as a fix.

- Notification:
We started preparing the notification since initial detection of the issue. But the delivery is delayed due to some issue.
From latest update, a notification mail with title `Reinstall open source component or fix with AKS integration` has been delivered to all affected subscription owners around `UTC 2023-03-10 03:00:00`. We'll keep improving on delivering the information in time.


Thank you again for taking the time to share your feedback with us. We appreciate your constructive comments, as they help us improve our products and services. We are always striving to deliver the best quality and value to our customers.

**Comment by lynkz-matt-psaltis** [comment] 2023-03-10 04:33
Thanks @karataliu! Can I add it is hugely appreciated that this type of RCA information is provided here. It helps us to build trust with our clients that this is being resolved quickly by the experts on the problem! So thanks on behalf of our team and our clients! Thank you also to everyone who has contributed to this thread, we were able to get actionable information in a short time frame which for a GitHub issue is fantastic! How times have changed :D

**Comment by aramase** [comment] 2023-03-13 16:44
Closing this issue with https://github.com/Azure/azure-workload-identity/issues/777#issuecomment-1463218209

**Closed by aramase** 2023-03-13 16:44 UTC
Labels: bug, aks
