### ISSUE TITLE
Please increase the number of allowed federated identity credentials that can be created for managed identity

### ISSUE THREAD

**Issue by MageshSrinivasulu** [Azure/azure-workload-identity#1172] opened 2023-11-07 13:11 UTC
Currently as per the documentation maximum of 20 federated identity credentials can be created for managed identity which is much less. Think about a scenario where 40-50 service accounts are there in the namespace for which federated identity credentials need to be created.

This restriction is literally blocking us from migrating to workload identity from the aad pod identity

![image](https://github.com/Azure/azure-workload-identity/assets/79187874/5422cc9e-e086-4c1f-8e33-af43b51c5f6b)

https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation-considerations#general-federated-identity-credential-considerations

**Comment by MageshSrinivasulu** [comment] 2023-11-14 08:56
If others in the community are facing similar issues, please upvote here. So that the MFST product team can consider those feature enhancement https://feedback.azure.com/d365community/idea/d172a504-ced3-ed11-a81c-6045bdb23064

**Comment by aramase** [comment] 2023-11-29 00:51
This is duplicate of https://github.com/Azure/azure-workload-identity/issues/575

@MageshSrinivasulu thanks for opening the issue. We are working with the AAD team for potential workarounds with the 20 FIC limitation. We'll update the other issue as we make progress.

Closing as duplicate.

**Closed by aramase** 2023-11-29 00:51 UTC
Labels: enhancement
