### ISSUE TITLE
Allow wildcards to identify subject

### ISSUE THREAD

**Issue by tobiasdiez** [Azure/azure-workload-identity#1118] opened 2023-09-16 09:57 UTC
**Is your feature request related to a problem? Please describe.**

I want to grant the federated token to workflows across various branches within the repository (without using environments due to other constraints). 

**Describe the solution you'd like**

Allow to match subject/branches with wildcards, such as `repo:MY_ORG/MY_REPO:*`

**Describe alternatives you've considered**

**Additional context**

https://github.com/Azure/login/issues/346

**Comment by chandlerkent** [comment] 2023-10-04 15:25
FYI duplicate of #373

**Comment by aramase** [comment] 2023-11-29 00:58
Thanks for opening the issue. This is duplicate of #373.

Please use that issue to track the rollout status of the AAD feature.

**Closed by aramase** 2023-11-29 00:58 UTC
Labels: enhancement
