### ISSUE TITLE
Should we create a new service account in every namespace?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/azure-workload-identity#903] opened 2023-04-27 18:11 UTC
Hello,

We have multiple environments divided into different namespaces. Is it possible to create only one service account in default namespace and refer it within the pods in other namespaces to enable trusted connectivity with the azure resources. 

As far as I remember, in aad pod identity, we just have to add the label in pod definition and it's enough to enable the connectivity with the azure resources. Can we do something like this. As it is very difficult to create kubernetes service account in every namespace. 

@aramase  Is my understand correct?

Kind Regards,
Tanul

**Comment by aramase** [comment] 2023-04-27 18:48
> As far as I remember, in aad pod identity, we just have to add the label in pod definition and it's enough to enable the connectivity with the azure resources. Can we do something like this. As it is very difficult to create kubernetes service account in every namespace.

Workload identity is based on OIDC federation and it is designed with projected service account. In case of aad-pod-identity, the default option allowed referencing `AzureIdentity` from default namespace by using the label which is not secure. Any pod can access the `AzureIdentity` with this. The recommendation with pod identity was to use it in namespaced mode, so only `AzureIdentity` within the same namespace can be referenced. 

This is duplicate of https://github.com/Azure/azure-workload-identity/issues/837.

As mentioned in the other thread, Kubernetes service accounts are namespaced resources, so you need to create in the same namespace as the pod to be able to reference it.

**Closed by aramase** 2023-04-27 18:48 UTC

**Comment by smartaquarius10** [comment] 2023-04-27 20:20
@aramase got it. Thanks.

**Comment by smartaquarius10** [comment] 2023-04-27 20:33
@aramase one more query. We just add service details in pod. And then we can call key vault via C# as well right?

or, do we have to make some specific changes in code as well.
